include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/firebase_options_*.dart"
    - "pubspec.yaml"
  errors:
    invalid_annotation_target: ignore
