name: trip_tonic
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Loading
  loading_animation_widget: ^1.2.0+4

  # Firebase
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10

  # State Management
  hooks_riverpod: ^2.3.1
  flutter_hooks: ^0.18.6

  # Navigator
  go_router: ^6.2.0

  # Logger
  logger: ^1.2.2

  # Secure
  flutter_config: ^2.0.0

  # Map
  google_maps_flutter: ^2.2.5

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  lyrebird: ^0.5.0+1

  # API Client
  retrofit: ^4.0.1

  # Bottom Navigation
  animated_bottom_navigation_bar: ^1.2.0

  # Other
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  gap: ^2.0.1
  custom_sliding_segmented_control: ^1.7.4
  draggable_home: ^1.0.4
  accordion: ^2.5.1
  dio: ^5.0.2
  geocoding: ^2.1.0
  google_place: ^0.4.7
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  flutter_lints: ^2.0.0
  pedantic_mono: ^1.21.1

  # Dev
  device_preview: ^1.1.0
  build_runner: ^2.3.3
  flutter_gen_runner:
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/map_style.json
