name: trip_tonic
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10

  # Other
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  flutter_lints: ^2.0.0
  pedantic_mono: ^1.21.1

  # Dev
  device_preview: ^1.1.0

flutter:
  uses-material-design: true
