# FirestoreのDB設計

version:
  users:
    documentId: auto
    name: string
    iconUrl: string
    createdAt: date
    updatedAt: date
    # 有料会員かどうかのフラグはCustomClaimsに設定している[IS_PREMIUM_MEMBER]でチェックする。

    notification:
      documentId: auto
      title: string
      content: string
      isRead: boolean
      createdAt: date
      updatedAt: date

  stories:
    id: auto
    userId: string
    title: string
    content: string
    backgroundImage: string
    latlng: map
    createdAt: date
    updatedAt: date

  favorites:
    id: auto
    userId: string
    storyId: string
    createdAt: date

makers:
  id: auto
  genre: string
  location: string
  latlng: map
  createdAt: date

genres:
  genre: string
