name: Check and test the source code
on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v3
      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.7"
          cache: false
      - name: Install packages
        run: flutter pub get
      - name: Linter
        run: flutter analyze
      - name: Test
        run: flutter test
